### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by SamAriafar** [Dubzer/TgTranslator#7]
I'm still receiving build errors on VS:

![image](https://user-images.githubusercontent.com/8606282/75281068-e3a13200-580e-11ea-9f89-0e6fe812a0bb.png)

```
25/02/2020 20:29:43
System.AggregateException: One or more errors occurred. ---> System.Exception: Build failed. Check the Output window for more details.
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.WebTools.Publish.PublishService.VsWebProjectPublish.<>c__DisplayClass43_0.<PublishAsync>b__3()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Publish.Framework.ViewModel.ProfileSelectorViewModel.<RunPublishTaskAsync>d__213.MoveNext()
---> (Inner Exception #0) System.Exception: Build failed. Check the Output window for more details.<---

System.Exception: Build failed. Check the Output window for more details.

===================
```

 Also on Linux machine:

```
Exceptions/InvalidSettingValueException.cs(5,18): warning RCS1194: Implement exception constructors. [/root/TgTranslator/src/TgTranslator.csproj]
Exceptions/UnauthorizedSettingChangingException.cs(5,18): warning RCS1194: Implement exception constructors. [/root/TgTranslator/src/TgTranslator.csproj]
Exceptions/UnsupportedCommand.cs(5,18): warning RCS1194: Implement exception constructors. [/root/TgTranslator/src/TgTranslator.csproj]
Exceptions/UnsupportedMenuItem.cs(5,18): warning RCS1194: Implement exception constructors. [/root/TgTranslator/src/TgTranslator.csproj]
```

**Comment by Dubzer** [comment]
Hi. It's not an error, it's just a warning and you shouldn't care about it

**Comment by Dubzer** [comment]
About your stacktrace: are you sure that .NET core SDK is installed properly?

**Comment by Dubzer** [comment]
It builds completely fine on my machine
![image](https://user-images.githubusercontent.com/18244287/75341113-c7e86b00-58a4-11ea-9dfa-0cb403bbda26.png)

**Comment by SamAriafar** [comment]
Well, I tried to publish it to my server using VS and it came back with those errors that stopped the process. But I guess you are right because on the Linux machine, I ignored these errors and I could go with further steps without any problem so far.
